#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import {
  INFISICAL_AUTH_ENV,
  INFISICAL_CONFIG,
  SECRETS_SCRIPT_DESCRIPTIONS,
} from "./lib/secrets-config.mjs";

const GENERATED_NOTICE =
  "<!-- Generated by `node scripts/generate-docs.mjs`. Do not edit manually. -->";

function parseEnvExample(text) {
  const entries = [];
  let commentBuffer = [];

  const flushComments = () => {
    commentBuffer = [];
  };

  for (const rawLine of text.split(/\r?\n/)) {
    const trimmed = rawLine.trim();

    if (!trimmed) {
      flushComments();
      continue;
    }

    const envMatch = rawLine.match(/^\s*(#\s*)?([A-Z0-9_]+)=(.*)$/);
    if (envMatch) {
      const commented = Boolean(envMatch[1]);
      const key = envMatch[2];
      const description = commentBuffer
        .filter((line) => line && !/^[=\-_*]+$/.test(line))
        .join(" ")
        .replace(/^Optional:\s*/i, "")
        .replace(/\s+/g, " ")
        .trim();

      entries.push({
        key,
        required: commented ? "No" : "Yes",
        description: description || (commented ? "Optional." : "Required."),
      });
      flushComments();
      continue;
    }

    if (trimmed.startsWith("#")) {
      const comment = trimmed.replace(/^#\s?/, "").trim();
      if (
        comment &&
        !comment.startsWith("CHRONICLE") &&
        !comment.startsWith("===") &&
        !comment.startsWith("---")
      ) {
        commentBuffer.push(comment);
      }
      continue;
    }

    flushComments();
  }

  return entries;
}

function renderTable(headers, rows) {
  const headerRow = `| ${headers.join(" | ")} |`;
  const separatorRow = `| ${headers.map(() => "---").join(" | ")} |`;
  const bodyRows = rows.map((row) => `| ${row.join(" | ")} |`);
  return [headerRow, separatorRow, ...bodyRows].join("\n");
}

async function renderEnvironmentDoc() {
  const agentExample = await fs.readFile("agent/.env.example", "utf8");
  const frontendExample = await fs.readFile("frontend/.env.example", "utf8");
  const agentRows = parseEnvExample(agentExample).map((entry) => [
    `\`${entry.key}\``,
    entry.required,
    entry.description,
  ]);
  const frontendRows = parseEnvExample(frontendExample).map((entry) => [
    `\`${entry.key}\``,
    entry.required,
    entry.description,
  ]);

  return [
    GENERATED_NOTICE,
    "# Environment",
    "",
    "Generated from `agent/.env.example` and `frontend/.env.example`.",
    "",
    "## Agent",
    "",
    renderTable(["Variable", "Required", "Description"], agentRows),
    "",
    "## Frontend",
    "",
    renderTable(["Variable", "Required", "Description"], frontendRows),
    "",
    "## Notes",
    "",
    "- Only `VITE_*` variables are exposed to the frontend bundle.",
    "- Never place secrets in `frontend/.env*`; frontend env is public by design.",
    "- `AUTH_SECRET` signs Chronicle session tokens; keep it server-only.",
    "",
  ].join("\n");
}

async function renderSecretsDoc() {
  const packageJson = JSON.parse(await fs.readFile("package.json", "utf8"));
  const secretScripts = Object.entries(packageJson.scripts)
    .filter(([name]) => name.startsWith("secrets:") || name.startsWith("virtuals:") || name.startsWith("docs:"))
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name]) => [
      `\`npm run ${name}\``,
      SECRETS_SCRIPT_DESCRIPTIONS[name] || packageJson.scripts[name],
    ]);

  const environmentRows = Object.values(INFISICAL_CONFIG.environments).map((envConfig) => [
    `\`${envConfig.name}\``,
    `\`${envConfig.workingFile}\``,
    `\`${envConfig.localMirrorFile}\``,
    `\`${envConfig.infisicalBackupFile}\``,
    `\`${envConfig.expectedAcpNetwork}\``,
  ]);

  const authRows = INFISICAL_AUTH_ENV.map((entry) => [
    `\`${entry.name}\``,
    entry.required,
    entry.description,
  ]);

  return [
    GENERATED_NOTICE,
    "# Secrets",
    "",
    "Generated from `scripts/lib/secrets-config.mjs` and root `package.json`.",
    "",
    "Infisical is Chronicle's shared source of truth. Local `.env` files remain the working copies for development and deployment, and `tmp/secrets/` holds ignored mirrors and snapshots.",
    "",
    "## Infisical",
    "",
    renderTable(
      ["Field", "Value"],
      [
        ["Domain", `\`${INFISICAL_CONFIG.domain}\``],
        ["Project ID", `\`${INFISICAL_CONFIG.projectId}\``],
        ["Secret Path", `\`${INFISICAL_CONFIG.secretPath}\``],
        ["Secret Type", `\`${INFISICAL_CONFIG.secretType}\``],
      ],
    ),
    "",
    "## Files",
    "",
    renderTable(
      ["Env", "Working File", "Local Mirror", "Infisical Snapshot", "Expected ACP Network"],
      environmentRows,
    ),
    "",
    "## Auth Env",
    "",
    renderTable(["Variable", "Requirement", "Description"], authRows),
    "",
    "## Commands",
    "",
    renderTable(["Command", "Purpose"], secretScripts),
    "",
    "## Safety Rules",
    "",
    "- `.env`, `.env.phala`, and `tmp/` are gitignored.",
    "- `tmp/secrets/*.local.env` are local mirrors from the working env files.",
    "- `tmp/secrets/*.env` are snapshots pulled from Infisical.",
    "- Live Infisical pull/push/backup commands require the auth env listed above in the current shell.",
    "- `scripts/infisical-sync.mjs` uses the Infisical API directly and requests `type=shared` so self-hosted shared secrets resolve correctly.",
    "- Run `npm run secrets:doctor` before deploys or after secret changes.",
    "",
  ].join("\n");
}

async function writeGeneratedFile(filePath, contents, checkOnly) {
  let current = "";
  try {
    current = await fs.readFile(filePath, "utf8");
  } catch {
    current = "";
  }

  if (checkOnly) {
    if (current !== contents) {
      throw new Error(`${filePath} is out of date. Run npm run docs:generate.`);
    }
    return;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, "utf8");
  console.log(`Generated ${filePath}`);
}

async function main() {
  const checkOnly = process.argv.includes("--check");
  const environmentDoc = await renderEnvironmentDoc();
  const secretsDoc = await renderSecretsDoc();

  await writeGeneratedFile("dev-docs/docs/environment.md", environmentDoc, checkOnly);
  await writeGeneratedFile("dev-docs/docs/secrets.md", secretsDoc, checkOnly);
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
